[package]
name = "jetxl"
version = "0.2.4-alpha"
edition = "2021"
authors = ["Omar Irfan Khan"]
description = "Blazing fast xlsx writer"
readme = "README.md"


[lib]
name = "jetxl"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["chrono", "chrono-tz","extension-module"] }
pyo3-arrow = "0.17"
arrow = "58"
arrow-array = "58"
arrow-schema = "58"
arrow-data = "58"
mtzip = { version = "4.0.3", features = ["rayon"] }
chrono = "0.4"
zmij = "1.0"
itoa = "1.0"
memchr = "2.7"
sha2 = "0.10"
base64 = "0.22"
rand = "0.9"
rayon = "1.10"
rustc-hash = "2.0"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "bmp"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

