[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "jetxl"
requires-python = ">=3.10"
readme = "README.md"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

license = "Apache 2.0"
license-files = ["LICEN[CS]E*"]

dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/omarirfa/Jetxl"
Issues = "https://github.com/omarirfa/Jetxl/issues"

[tool.maturin]
features = ["pyo3/extension-module"]