[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "jetxl"
description = "Blazingly fast Excel writer for Python, powered by Rust"
requires-python = ">=3.10"
readme = "README.md"
authors = [{ name = "Omar Irfan Khan" }]
keywords = ["excel", "xlsx", "rust", "arrow", "polars", "pandas", "spreadsheet"]
license = "Apache-2.0"
license-files = ["LICEN[CS]E*"]
dynamic = ["version"]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Office/Business :: Financial :: Spreadsheet",
]

[project.urls]
Homepage = "https://github.com/omarirfa/jetxl"
Issues = "https://github.com/omarirfa/jetxl/issues"

[tool.maturin]
features = ["pyo3/extension-module"]
