#!/usr/bin/env python3
"""
Parallel single-sheet row-generation — correctness guard.

The single-sheet Arrow writer generates row XML in parallel chunks when the sheet
is large enough and more than one worker thread is available. This test locks in
the two properties that make that optimization safe:

  1. DETERMINISM: the same input produces byte-identical output across repeated
     runs (chunk concatenation order is stable, shared-string indices stable).
  2. SERIAL/PARALLEL PARITY: the worksheet XML is identical whether generated by
     the parallel path (forced on via a multi-thread rayon pool) or the serial
     path — i.e. parallelizing changes not one output byte.

Because the CI sandbox may have a single core, this test can be run with
RAYON_NUM_THREADS=N (N>1) to force the parallel branch. It asserts internal
consistency (run-to-run determinism) unconditionally, which catches races and
non-deterministic ordering regardless of core count.

Usage: python test_parallel_rows.py           (determinism only, any core count)
       RAYON_NUM_THREADS=4 python test_parallel_rows.py   (also exercises parallel)
"""
from __future__ import annotations

import datetime as dt
import io
import sys
import zipfile

import pyarrow as pa

import jetxl

_p = _f = 0


def check(desc, cond):
    global _p, _f
    if cond:
        _p += 1
    else:
        _f += 1
        print(f"  FAIL {desc}")


def ws_bytes(b):
    return zipfile.ZipFile(io.BytesIO(b)).read("xl/worksheets/sheet1.xml")


def make_table(n, seed=0):
    import random
    r = random.Random(seed)
    base = dt.date(1970, 1, 1)
    return pa.table({
        "id": pa.array(range(n), pa.int64()),
        "val": pa.array([i * 1.5 for i in range(n)], pa.float64()),
        "name": pa.array([f"row_{i}_{r.randint(0, 99)}" for i in range(n)]),
        "flag": pa.array([i % 2 == 0 for i in range(n)]),
        "when": pa.array([base + dt.timedelta(days=i % 20000) for i in range(n)], pa.date32()),
    })


def test_determinism():
    # Large enough to cross the parallel threshold (50k rows).
    for n in [55_000, 100_000, 200_000]:
        t = make_table(n, seed=n)
        outs = [ws_bytes(jetxl.write_sheet_arrow_to_bytes(t, column_formats={"when": "date"}))
                for _ in range(4)]
        check(f"[n={n}] deterministic across 4 runs", all(o == outs[0] for o in outs))
        # with features that touch the per-row path
        outs2 = [ws_bytes(jetxl.write_sheet_arrow_to_bytes(
            t, hidden_rows=[10, 500, 40_000], write_header_row=False)) for _ in range(3)]
        check(f"[n={n}] deterministic with hidden_rows/no-header", all(o == outs2[0] for o in outs2))


def test_chunk_boundary_row_numbers():
    # Verify row numbers are correct across chunk boundaries: read back a handful
    # of scattered rows and confirm the id column equals the row index.
    import openpyxl
    n = 120_000
    t = pa.table({"id": pa.array(range(n), pa.int64())})
    b = jetxl.write_sheet_arrow_to_bytes(t)
    wsheet = openpyxl.load_workbook(io.BytesIO(b), read_only=True).active
    # header at row 1, data starts row 2 -> data value at excel row r is (r-2)
    probes = [2, 3, 49_999, 50_000, 50_001, 99_999, 100_001, n + 1]
    rows = {c.row: c.value for row in wsheet.iter_rows() for c in row if c.row in probes}
    ok = all(rows.get(r) == r - 2 for r in probes if r in rows)
    check("row numbers correct across chunk boundaries", ok and len(rows) == len(probes))


def main():
    import os
    nthreads = os.environ.get("RAYON_NUM_THREADS", "(default)")
    print("=" * 70)
    print(f"parallel single-sheet row generation — correctness guard")
    print(f"RAYON_NUM_THREADS = {nthreads}")
    print("=" * 70)
    test_determinism()
    test_chunk_boundary_row_numbers()
    print("-" * 70)
    print(f"TOTAL: {_p} passed, {_f} failed")
    print("=" * 70)
    return 1 if _f else 0


if __name__ == "__main__":
    sys.exit(main())
